name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Build and run tests

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build solution
      - run: dotnet build BDMS.sln /warnaserror
      
      - name: Start db and api's
        run: docker-compose up -d minio db api-legacy api

      - name: Run dotnet tests
      - run: dotnet test BDMS.sln --no-build --verbosity normal

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - working-directory: ./src/client
        run: npm ci

      - working-directory: ./src/client
        run: npm run lint

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build --if-present
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          working-directory: ./src/client
